name: shelf_letsencrypt
description: Let's Encrypt support for the shelf package (free and automatic HTTPS certificate support).
version: 1.1.1
homepage: https://github.com/gmpassos/shelf_letsencrypt

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path: ^1.8.2
  shelf: ^1.4.0
  acme_client:
    git:
      url: https://github.com/NOU-VANNET/acme_client.git
      ref: main
  basic_utils: ^5.5.0
  coverage: ^1.6.3
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
  dependency_validator: ^3.2.2
